Added classes ClassicMusic, MusicStyles, PopMusic, RockMusic
AlinaKlishyna/KlishynaAlina_JavaBase pull request #21
Opened 2024-02-20 18:44 UTC by AlinaKlishyna

2024-02-21 20:57 UTC, JIeIIIa requested changes

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +public class ClassicMusic extends MusicStyles{
Форматування коду

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +        return String.format("Play \"%s\"- %s music", group, getStyle());
Якщо гетер тільки повертає значення поля, то немає ніяких переваг використовувати його в середині класу. Краще "працювати" з полем.

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +    private String style;
Навіщо тобі поле, якщо з гетера ти повертаєш константу? Якщо ти додаєш якийсь функціонал, то його використання має бути виправданим

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +    public ClassicMusic(String group) {
Спочатку в класи статичні поля, потім поля, далі конструктори, гетери/сетери і потім решта методів. Коли всі класи мають певну структуру, то простіше орієнтуватись. У тебе ж спочатку гетер, а потім конструтор. чому так?

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/MusicRunner.java
> +        MusicStyles[] musicStyles = new MusicStyles[3];
Не помилка, але так було б зробити простіше
```
MusicStyles[] musicStyles = {new ClassicMusic("Mozart"),
        new PopMusic("BTS"),
        new RockMusic("Led Zeppelin")
}
```

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/MusicRunner.java
> +            System.out.println(element.playMusic(element.group));
А чому метод playMusic у тебе приймає ще якийсь параметр. Хіба даний метод може бути викликаний з будь-яким рядком? Кожен гурт за умовою грає в якомусь стилі. У дуже дивно, якщо я буду робити:
```
MusicStyles band = new ClassicMusic("Mozart");
band.playMusic("HARD METAL");
```

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/MusicStyles.java
> +    public String playMusic(String group) {
Клас має поле група, даний метод приймає параметр група і повертає цей же параметр. Скажи, а навіщо тоді взагалі цей метод? Передати рядок щоб отримати цей же рядок? Так мені простіше рядок одразу почати використовувати без якихось "проміжних" методів.

Інше питання: а чому тут взагалі є реалізація? Це ж якийсь невизначений стиль, наче.

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/PopMusic.java
> +    public String playMusic(String group) {
Клас має поле група, але мені групу потрібно ще в якості параметра передати? Навіщо тоді в класі поле `group`?

2024-02-21 20:57 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task18/PopMusic.java
> +        playMusic(group);
Чому під час створення обʼєкту одразу щось відбувається? Можеш трактувати це як "поки не організують концерт група не має нічого грати. але до початку концерта група має існувати"

2024-02-24 10:14 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +public class ClassicMusic extends MusicStyles{
виправлено

2024-02-24 10:16 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +        return String.format("Play \"%s\"- %s music", group, getStyle());
Виправлено(видалила метод getStyle() та ініціалізувала значення змінної style)

2024-02-24 10:19 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +    private String style;
Виправлено

2024-02-24 10:22 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/ClassicMusic.java
> +    public ClassicMusic(String group) {
Згодна, краще орієнтуватись, щоб першим був конструктор після полів, а вже потім наступні методи

2024-02-24 10:23 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/MusicRunner.java
> +        MusicStyles[] musicStyles = new MusicStyles[3];
Я щось в перший раз не здогадалась, що можна було б не вказувати розміри

2024-02-24 10:58 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/MusicRunner.java
> +        MusicStyles[] musicStyles = new MusicStyles[3];
і при цьому не створюючи тип об'єкту

2024-02-24 11:07 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/MusicRunner.java
> +            System.out.println(element.playMusic(element.group));
Я зараз ще думаю як правильно воно працює(я вже зробила, думаю в цей раз вірно)

Мої думки такі: 
1.  є клас MusicStyles(вже він абстрактний без тіл методів) і він містить якісь "взаємозалежні методи"(тобто як "їсти" між собакою/кішкою) і в нього є метод
playMusic()(який відповідає за грання музики)

2. в класі MusicStyles є метод playMusic()(який відповідає за грання музики) і який **_має приймати параметр - ім'я групи_**
3. І в цьому була загвоздка: яке значення я маю передати MusicStyles , щоб брались значення наслідників

Мабуть, зараз я зрозуміла.. клас-батько по суті він має бути реалізованим як наче не для багатьох класів(як я додала назву групи), а лише для одного? Чи віпрно я зрозуміла?

2024-02-24 11:09 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/MusicStyles.java
> +    public String playMusic(String group) {
Виправлено:
Зробила його абстрактним класом без тіл методів

2024-02-24 11:20 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/PopMusic.java
> +        playMusic(group);
Виправлено: видалено рядок #7

2024-02-24 11:27 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/PopMusic.java
> +    public String playMusic(String group) {
Тут згодна, бо в батьківському класі вже є

2024-02-24 11:27 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task18/PopMusic.java
> +    public String playMusic(String group) {
Тут згодна, бо в батьківському класі вже є

2024-02-24 17:43 UTC, JIeIIIa approved these changes

2024-03-01 22:55 UTC, merged