Added classes Point and PointRunner
AlinaKlishyna/KlishynaAlina_JavaBase pull request #22
Opened 2024-02-24 16:20 UTC by AlinaKlishyna

In Class Point added constructors, getters and setters, also 2 methods: currentCoordinates() and distance()

In class PointRunner added method main() with point of entry

2024-02-25 21:49 UTC, JIeIIIa requested changes

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +        if (o == null || getClass() != o.getClass() | !(o instanceof Point)) {
Чому тут використовується не скорочене логічне АБО `||`, а звичайне `|` ? Мати `getClass` та `instanceof` одночасно - зайве. Визначись як ти хочеш виконувати порівняння: якщо класи не співпадають, то об'єкти не рівні. Чи якщо у тебе є точка і кольорова точка (нащадок точки), то ти вважаєш такі об'єкти рівними при співпадінні координат

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +        return getDistance(getX(), getY(), point.getX(), point.getY());
Який сенс тут використовувати гетер? Вже було подібне зауваження. На останній лекції про це казав. І все одно виклик гетера... Мова про ``` getX(), getY() ```

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(Point pointInit, Point pointFinal) {
Чому б параметри не назвати просто `init` та `final`? Хіба по типу даних не буде зрозуміло що це точки?

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(int xA, int yA, int xB, int yB) {
Даний метод робити не просили. Він зайвий. Те саме можна було зробити в одному з двох методів вище і перевикористати його.

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +        return String.format("%s (%d; %d)", getClass().getSimpleName(), getX(), getY());
Тут простіше було б написати `"Point(%d; %d)"` замість `getClass().getSimpleName()`. Навіщо кожен раз викликати два методи?

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public Point clone() throws CloneNotSupportedException {
Не вистачає анотації `@Override`. Коли перевизначаємо метод завжди використовуємо цю анотацію. Інакше замість перевизначення можна випадково перевантажити (зробити overload) методів і програма буде працювати не так, як очікуєш

2024-02-25 21:49 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/PointRunner.java
> +        System.out.println(pointA.getDistance(pointA, pointB));
Так зліва вже є `pointA`. Навіщо мені його ще раз передавати як параметр? З іншого боку я можу викликати метод як 
```
Point anotherPoint = new Point(0, 0);
pointA.getDistance(anotherPoint, pointB);
```
Проблема в тому, що метод реалізовано не вірно. Хоча параметри в методах вірні)

І ще одна проблема: що буде, якщо у метод передадуть `null`?

2024-02-26 16:55 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +        return getDistance(getX(), getY(), point.getX(), point.getY());
Виправила на просто х/у

2024-02-26 16:58 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(Point pointInit, Point pointFinal) {
Згодна.
Змінила на init та end, тому що "final" це зарезервоване слово як для змінної

2024-02-26 17:03 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(int xA, int yA, int xB, int yB) {
```java
public double getDistance(Point point) {
        return Math.sqrt((Math.pow((point.x - x), 2) + (Math.pow((point.y- y), 2))));
    }

    public double getDistance(Point init, Point end) {
        return Math.sqrt((Math.pow((end.x - init.x), 2) + (Math.pow((end.y - init.y), 2))));
    }
``` 

- зробила таким чином

2024-02-26 17:05 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(int xA, int yA, int xB, int yB) {
```java
 public double getDistance(Point end) {
        Point init = new Point(x,y);
        return getDistance(init, end);
    }

    public double getDistance(Point init, Point end) {
        return Math.sqrt((Math.pow((end.x - init.x), 2) + (Math.pow((end.y - init.y), 2))));
    }
``` 
- таким чином перевикористала метод, та видалила минулий

2024-02-26 17:07 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +        if (o == null || getClass() != o.getClass() | !(o instanceof Point)) {
```java
if (o == null || !(o instanceof Point))
``` 
Так, краще взяти щось одне

2024-02-26 17:10 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +        return String.format("%s (%d; %d)", getClass().getSimpleName(), getX(), getY());
Добре, думала б краще показати назву класу.. Видалила

2024-02-26 17:12 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public Point clone() throws CloneNotSupportedException {
Зрозуміла, додала

2024-02-26 17:22 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/PointRunner.java
> +        System.out.println(pointA.getDistance(pointA, pointB));
Реалізовано в цілому не правильно, чи лише тому що "null"?

2024-02-26 17:32 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/PointRunner.java
> +        System.out.println(pointA.getDistance(pointA, pointB));
```java
 if (init == null || end == null){
            System.out.println("One of the points is null!");
            return 0.0;
        }
``` 
Змінила таким чином

2024-02-29 11:34 UTC, JIeIIIa requested changes

2024-02-29 11:34 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +        int result = 31;
так варто робити, якщо зп залежить від кіл-сті написаних рядків коду))) достатньо було просто
```
return 31 * x + y;
```

2024-02-29 11:34 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +        if (this == o) return true;
Code conventions! Навіть якщо до `if` відноситься тільки один оператор ми все одно застосовуємо {...} На заняття я попереджав що буде мінус за це

2024-02-29 11:34 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public double getDistance(int xA, int yA, int xB, int yB) {
Молодець. Все вірно зробила

2024-02-29 11:34 UTC, JIeIIIa commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public int getY() {
Зараз тільки 2 поля, тому за помилку я це не вважаю, але... все ж краще попарно розташовувати гетер-сетер для полів. Тобто мало б бути getY, setY, getX, setX. Тоді простіше розуміти для якого поля який метод для доступу є. На лекціях про це також було декілька разів;)

2024-02-29 12:34 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +    public int getY() {
Зрозуміла, щоб краще було їх находити

2024-02-29 12:35 UTC, AlinaKlishyna commented on src/com/gmail/alinakotova102/task19/Point.java
> +        if (this == o) return true;
Додала

2024-02-29 12:42 UTC, JIeIIIa approved these changes

2024-03-01 22:54 UTC, merged